CREATE TABLE ORDERS(
    ORDERID INT PRIMARY KEY NOT NULL,
    CUSTOMERID INT NOT NULL,
    ORDERDATE DATE NOT NULL
);

CREATE TABLE ORDER_DETAILS(
    ORDERID INT NOT NULL REFERENCES ORDERS,
    PRODUCTID INT NOT NULL,
    UNITPRICE INT NOT NULL,
    QUANTITY INT NOT NULL
);
